// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWhLMBcUfNYi2VM9806S1y3cOfsbHntBU',
    appId: '1:198411346858:web:05d805ba6ed2513eab41d3',
    messagingSenderId: '198411346858',
    projectId: 'pisiit',
    authDomain: 'pisiit.firebaseapp.com',
    storageBucket: 'pisiit.appspot.com',
    measurementId: 'G-63CQ1DWYPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsfsGhwHBsEa6olqChMElSA_rG5xPqwlc',
    appId: '1:198411346858:android:9a771595d25954edab41d3',
    messagingSenderId: '198411346858',
    projectId: 'pisiit',
    storageBucket: 'pisiit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMg6yRfkLgEm0Gh9_vmbrCCwun0fuA2Qo',
    appId: '1:198411346858:ios:48e21b01ee57bae7ab41d3',
    messagingSenderId: '198411346858',
    projectId: 'pisiit',
    storageBucket: 'pisiit.appspot.com',
    iosBundleId: 'com.example.pisiit',
  );
}
